### ISSUE TITLE
Confused information in the log file

### ISSUE THREAD

**Issue by JhinAir** [xjtu-omics/SVision#25]
Hi,
Thanks for the great software! I think I have successfully run the pipeline and got normal results. However I got such error information in the log file:
> INFO:tensorflow:Restoring parameters from /public/home/wjj/Bioapp/SVision/svision_model/svision-cnn-model.ckpt
Traceback (most recent call last):
  File "/public/home/wjj/miniconda3/envs/svisionenv/bin/SVision", line 4, in <module>
    __import__('pkg_resources').run_script('SVision==1.3.7', 'SVision')
  File "/public/home/wjj/miniconda3/envs/svisionenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/home/wjj/miniconda3/envs/svisionenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/public/home/wjj/miniconda3/envs/svisionenv/lib/python3.6/site-packages/SVision-1.3.7-py3.6.egg/EGG-INFO/scripts/SVision", line 463, in <module>
    collect_csv_same_format(graph_out_path, merged_vcf_path, options)
  File "/public/home/wjj/miniconda3/envs/svisionenv/lib/python3.6/site-packages/SVision-1.3.7-py3.6.egg/src/collection/graph.py", line 574, in collect_csv_same_format
    reads = record.info['READS']
  File "pysam/libcbcf.pyx", line 2573, in pysam.libcbcf.VariantRecordInfo.__getitem__
KeyError: 'Invalid INFO field: READS'
> 
It's due to the pysam version (mine is v0.16.0.1)? Would the final result be affected?  Thank you!
Best,
Jing

**Comment by jiadong324** [comment]
This will affect the generation of CSV graphs. Would please check whether 'READS' is your VCF info column.
