### ISSUE TITLE
truvari指标

### ISSUE THREAD

**Issue by Bigdata20688** [xjtu-omics/SVision#37]
我在使用HG00733.svision.s5.graph.vcf.gz结果文件和pav_HG00733_CLR_SS_FLYE_PA.vcf.gz基准文件使用Truvari进行基准测试查看准确率和召回率出现Traceback (most recent call last):
  File "/opt/conda/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/truvari/__main__.py", line 105, in main
    TOOLS[args.cmd](args.options)
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 766, in bench_main
    output = m_bench.run()
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 495, in run
    for match in itertools.chain.from_iterable(map(self.compare_chunk, chunks)):
  File "/opt/conda/lib/python3.9/site-packages/truvari/matching.py", line 327, in chunker
    if not matcher.filter_call(entry, key == 'base'):
  File "/opt/conda/lib/python3.9/site-packages/truvari/matching.py", line 164, in filter_call
    size = truvari.entry_size(entry)
  File "/opt/conda/lib/python3.9/site-packages/truvari/comparisons.py", line 362, in entry_size
    size = abs(entry.info["SVLEN"][0])
TypeError: bad operand type for abs(): 'str'

**Comment by jiadong324** [comment]
You might want to change the header of the PAV VCF header. The SVLEN in the info header should be somthing like this  ```##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">```.

Hope this help!

**Comment by Bigdata20688** [comment]
收到了嘻嘻。

**Comment by Bigdata20688** [comment]
您好，根据您的帮助我尝试在SVision生成的HG00733.svision.s5.graph.vcf文件中加入   ##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">后，然后运行 truvari bench -b /root/SVision/home/user/svision_out/HG00733.svision.s5.graph.vcf.gz -c /root/SVision/copmpare/pav_HG00733_CLR_SS_FLYE_PA.vcf.gz -o output_dir/进行指标分析，报了如下错误：Traceback (most recent call last):
  File "/opt/conda/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/truvari/__main__.py", line 105, in main
    TOOLS[args.cmd](args.options)
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 751, in bench_main
    if check_params(args) or check_inputs(args):
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 177, in check_inputs
    b_check, args.bSample = check_sample(args.base, args.bSample)
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 159, in check_sample
    vcf_file = pysam.VariantFile(vcf_fn)
  File "pysam/libcbcf.pyx", line 4117, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4347, in pysam.libcbcf.VariantFile.open
ValueError: invalid file `b'/root/SVision/home/user/svision_out/HG00733.svision.s5.graph.vcf.gz'` (mode=`b'r'`) - is it VCF/BCF format?

**Comment by Bigdata20688** [comment]
感谢您提供的帮助，但是按照您的操作，我尝试在pav_HG00733_CLR_SS_FLYE_PA.vcf文件开头加入您给的头部信息后，运行truvari bench -b /root/SVision/copmpare/pav_HG00733_CLR_SS_FLYE_PA.vcf.gz -c /root/SVision/home/user/svision_out/HG00733.svision.s5.graph.vcf.gz -o output_dir/该命令后，提示
Traceback (most recent call last):
  File "/opt/conda/bin/truvari", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/truvari/__main__.py", line 105, in main
    TOOLS[args.cmd](args.options)
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 751, in bench_main
    if check_params(args) or check_inputs(args):
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 177, in check_inputs
    b_check, args.bSample = check_sample(args.base, args.bSample)
  File "/opt/conda/lib/python3.9/site-packages/truvari/bench.py", line 159, in check_sample
    vcf_file = pysam.VariantFile(vcf_fn)
  File "pysam/libcbcf.pyx", line 4117, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4347, in pysam.libcbcf.VariantFile.open
ValueError: invalid file `b'/root/SVision/copmpare/pav_HG00733_CLR_SS_FLYE_PA.vcf.gz'` (mode=`b'r'`) - is it VCF/BCF format?错误，有没有解决办法呢？

**Comment by Bigdata20688** [comment]
> You might want to change the header of the PAV VCF header. The SVLEN in the info header should be somthing like this `##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">`.
> 
> Hope this help!

感谢您提供的帮助，但目前采用您的建议后遇到了问题，您可以再帮忙看一下吗？

**Comment by Bigdata20688** [comment]
或者您可以告诉一下我您的结果对比指标（准确率、召回率）是采用了什么方法吗？

**Comment by jiadong324** [comment]
We also use ```truvari bench``` in the paper, but it was a very old version of truvari (like v3.*)

Looks like it is the truvari issue, which version did you use? Please also check and confirm whether ```pav_HG00733_CLR_SS_FLYE_PA.vcf.gz``` is a valid VCF format or not. You can simply use ```bcftools view```.
