### ISSUE TITLE
ValueError while running the tool

### ISSUE THREAD

**Issue by Pigrenok** [xjtu-omics/SVision#5]
Hello!

As discussed in the other issue, I am trying to run SVision on minimap2 alignment of assembled sequence to reference genome. It uses artificial sequence with specially SV. Minimap2 seems to correctly describe it in CIGAR (looking at SAM file).

Minimap2 SAM file was converted to BAM and all indexes (for BAM and ref FASTA) were done using samtools.

When I run SVision on this case, I get the following output and ValueError at the end (it seems to be trying to find maximum of zero-size array, which is indeed an error):
```
# SVision --contig -o /data/out/ -b /data/alt.sorted.bam -g /data/ref.fa -m /data/models/svision-cnn-model.ckpt -n test
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2022-09-22 22:54:01.506259: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599955000 Hz
2022-09-22 22:54:01.514342: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x43c4750 executing computations on platform Host. Devices:
2022-09-22 22:54:01.514418: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2022-09-22 22:54:01.613511: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /data/models/svision-cnn-model.ckpt
Traceback (most recent call last):
  File "/usr/local/bin/SVision", line 437, in <module>
    max_score, min_score = cal_scores_max_min(predict_results_dir)
  File "/usr/local/lib/python3.6/dist-packages/src/network/output.py", line 661, in cal_scores_max_min
    return np.max(all_scores), np.min(all_scores)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2505, in amax
    initial=initial)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
[SVision_220922_225400.log](https://github.com/xjtu-omics/SVision/files/9629900/SVision_220922_225400.log)
``` 
The log does not seem to contain any errors:
```
2022-09-22 22:54:00,835 [INFO   ]  ******************** Start SVision, version 1.3.7 ********************
2022-09-22 22:54:00,835 [INFO   ]  CMD: /usr/local/bin/SVision --contig -o /data/out/ -b /data/alt.sorted.bam -g /data/ref.fa -m /data/models/svision-cnn-model.ckpt -n test
2022-09-22 22:54:00,835 [INFO   ]  WORKDIR DIR: /data/out
2022-09-22 22:54:00,835 [INFO   ]  CNN MODEL: /data/models/svision-cnn-model.ckpt
2022-09-22 22:54:00,836 [INFO   ]  INPUT BAM: /data/alt.sorted.bam
2022-09-22 22:54:00,837 [INFO   ]  
****************** Step1 Image coding and segmentation ******************
2022-09-22 22:54:00,902 [INFO   ]  Processing seq1:0-612000, 2 segments write to: seq1.segments.0.bed
2022-09-22 22:54:01,034 [INFO   ]  [Coding finished]: Collect segment signatures, Cost time: 0
2022-09-22 22:54:01,034 [INFO   ]  
****************** Step2 CNN prediction ******************
2022-09-22 22:54:01,167 [WARNING]  From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2022-09-22 22:54:02,197 [WARNING]  From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2022-09-22 22:54:02,199 [INFO   ]  Restoring parameters from /data/models/svision-cnn-model.ckpt
2022-09-22 22:54:04,307 [INFO   ]  Predicting seq1
2022-09-22 22:54:04,443 [INFO   ]  [Prediction finished]: Predicting types, Cost time: 3
```
In addition to this, I get the following files in the output directory:
out ->
 - predict_results ->
   - seq1.predict.s5.score.txt
   - seq1.predict.s5.vcf
 - segments ->
   - seq1.segments.0.bed
   - ....
   - seq1.segments.all.bed

All files are empty. Yes, 'seq1' is the name of the sequence in the reference FASTA `ref.fa`.

Also, I am running it in a Docker container based on your image.

Any idea why this is happening and what can be done to overcome this?

Thank you very much in advance.

**Comment by jiadong324** [comment]
Please first check if you have output in ```seq1.predict.s5.score.txt```. Thanks!

**Comment by Pigrenok** [comment]
No, as I said, all files generated (including seq1.predict.s5.score.txt) are empty.

**Comment by jiadong324** [comment]
Ok, it is largely caused by the non-closed writer in the threading. It was fixed in our latest push, please clone the code again and remove the previous one.

**Comment by Pigrenok** [comment]
I am glad to hear that you managed to find and fix this small bug.

As I said before, I ran SVision in Docker (using the image provided by you).

This time I built a docker image using your Dockerfile (which is cloning the repo in the process). I definitely removed all old images related to SVision beforehand.

Unfortunately, running SVision in the new container did not bring any joy. Still all output files are empty and the same error in the same place in the console output.

After that, I double checked the repo and I can see the last commit from 21 September (5 days ago), where I opened this issue only 3 days ago (23 September). I assume there was something wrong with your latest push, and it was not reflected in the repo yet.

**Comment by jiadong324** [comment]
Would you please clone the source code, and check if ```out_score_file.close()``` exist in line 302 of the file /src/network/predict.py. If it is there, please run from source code instead of using Docker. 

Thanks for helping me improve this tool!

**Comment by Pigrenok** [comment]
Here my local git log:

![image](https://user-images.githubusercontent.com/18658968/192312229-8cc3542c-2fb9-4cf2-a167-2a1c5e2cbfae.png)

So, the last commit from 21 September.

`out_score_file.close()` is in line 302 of the ./src/network/predict.py. Because I built my own docker image and it freshly cloned the repo, the same can be said about the code inside docker image: `out_score_file.close()` is in line 302 of the ./src/network/predict.py

I also tried to pull the repo again and create the environment, run SVision and got exactly the same behaviour.

Thank you very much for looking into this.

**Comment by jiadong324** [comment]
This is strange. Are you able to run the demo data?

**Comment by chenx-bob** [comment]
I got the same error in the newest push

**Comment by jiadong324** [comment]
@chenx-bob @Pigrenok Thanks for reporting this issue. This will be one of the major updates in the upcoming version (v1.3.8).

**Comment by Pigrenok** [comment]
Hello!

You can find the example that I use here:
https://yadi.sk/d/xDvDTW9sVCWYlA

These are purely generated sequences. Ref has the following blocks: s1Long - s1 - s2 - s3 - s4 - s2Long, whereas Alt has the following sequence s1Long + inverse(inverse(s1) + inverse(s3)) + s2 + s4 + s2Long
Here s1Long and s2Long are 300 kbp long each (independently generated) and s1, s2, s3 and s4 are 3 kbp long each, also generated independent of each other. I would not expect the absolutely correct output, but I want some output at least.

You can also find the alt.fa file (in the same folder) which contains the "variant" sequence itself if you want to do alignment yourself for testing.

I also tried to use your demo data, but because your reference is not available, I tried to download reference FASTA from RefSeq, but it seems to be unsuitable, I got the following log:

```
2022-09-27 11:26:44,173 [INFO   ]  ******************** Start SVision, version 1.3.7 ********************
2022-09-27 11:26:44,174 [INFO   ]  CMD: /home/pigrenok/.pyenv/versions/miniconda2-latest/envs/svisionenv/bin/SVision -o ./demo_out -b ./demo/HG00733.svision.demo.bam -m ./models/svision-cnn-model.ckpt -g ./demo/GCF_000001405.26_GRCh38_genomic.fna -n HG00733 -s 5 --graph --qname
2022-09-27 11:26:44,174 [INFO   ]  WORKDIR DIR: /mnt/storage/YandexDisk/Kew/1001G/GraphGeneration/TestingPipelines/sVision/demo_out
2022-09-27 11:26:44,174 [INFO   ]  CNN MODEL: /mnt/storage/YandexDisk/Kew/1001G/GraphGeneration/TestingPipelines/sVision/models/svision-cnn-model.ckpt
2022-09-27 11:26:44,177 [INFO   ]  INPUT BAM: /mnt/storage/YandexDisk/Kew/1001G/GraphGeneration/TestingPipelines/sVision/demo/HG00733.svision.demo.bam
2022-09-27 11:26:44,206 [ERROR  ]  No mapped reads in the BAM, please check your reference input!
```

If you can provide your reference that you used to align your demo data, I can try to run it.

**Comment by jiadong324** [comment]
@Pigrenok Thanks for sharing the data. I realize that you are detecting from assemblies, thus please activate the contig mode with ```--contig```. Please try the latest release V1.3.8.

Your simulated SV is a cut-and-paste event, which is a very special and interesting case compared to the copy-and-paste like events (e.g., inverted duplication). Currently, this cut-and-paste style is detected as INS and DEL, further optimization for measuring sequence similarity is required to determine whether they are one CSV event or not.

**Comment by Pigrenok** [comment]
If you look at the original post in this issue, you can see that `--contig` was used for my case. It was always used when I tried my case.

I did not use `--contig` only for your demo data. I used command as it is stated at the bottom of README.md.

I see you pushed two new commits and in particular added chromosome number option instead of hardcoding 24 for human genome.

I am wondering what do you expect as names of sequences in reference FASTA? Does it necessarily has to be named somehow or is it just the number of sequences in reference FASTA which plays the role? Does it have to be explicitly stated in the `--cn` parameter if it is not 24? For my case it should be 1? Or I do not understand the purpose of this parameter?

Thanks.

**Comment by jiadong324** [comment]
I am sorry for the confusion, I did not state very clear regarding to the latest update. Here are the explanations of what's going on:

1. Using V1.3.8, I have tested your data with ```--contig``` and it runs without errors.
2. The ```--cn``` parameter is ignored in the latest push, which is initially used to exclude alternative contigs in human reference genome. As a result, some people work on other species contain more than 24 chromosomes may not get SVs from chr25 and etc. For V1.3.8, SVision detect SVs from every chromosomes included in the reference file.

Please let me know if you are able to run the demo data and your own data.

Really appreciate your help to improve SVision!
